CREATE SCHEMA IF NOT EXISTS ds;
CREATE TABLE IF NOT EXISTS ds.deliveries (
    id SERIAL NOT NULL PRIMARY KEY,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    state VARCHAR(256) NOT NULL,
    pickup_lat DECIMAL(10,6) NOT NULL,
    pickup_lon DECIMAL(10,6) NOT NULL,
    dropoff_lat DECIMAL(10,6) NOT NULL,
    dropoff_lon DECIMAL(10,6) NOT NULL,
    zone_id VARCHAR(3) NOT NULL
    );

CREATE SCHEMA IF NOT EXISTS bs;
CREATE TABLE IF NOT EXISTS bs.bots (
    id SERIAL NOT NULL PRIMARY KEY,
    status VARCHAR(256) NOT NULL,
    lat DECIMAL(10,6) NOT NULL,
    lon DECIMAL(10,6) NOT NULL,
    zone_id VARCHAR(3) NOT NULL
    );